services:
  db:
    image: postgres:16.4
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=unicorns
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    image: unicorn-store-wildfly:latest
    environment:
      - DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/unicorns
      - DATASOURCE_PASSWORD=postgres
      - DATASOURCE_USERNAME=postgres
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "9990:9990"
